### ISSUE TITLE
Pullman's Palace Crashes Game

### ISSUE THREAD

**Issue by balaji-venkatesh** [EternalBlueFlame/Trains-In-Motion#22]
Whilst placing the Pullman's Palace, the game crashes.

The error report is as so:

```
The game crashed whilst ticking entity
Error: java.lang.ArrayIndexOutOfBoundsException: 4
```

This happens every time, so it is probably a bug.

**Comment by balaji-venkatesh** [comment]
Now that it's in the world, I can't open it...

**Comment by NitroxydeX** [comment]
The error report doesn't say anything. Post the full error log to pastebin and link it here.

**Comment by EternalBlueFlame** [comment]
I know this issue, I fixed it a while ago, but I haven't released a bugfix build yet because I'm still fixing other known bugs.
